name: Generate Expeditions Map

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Expeditions repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run geojson_generate_expeditions.py
        run: python geojson_generate_expeditions.py

      - name: Run html_generate_expeditions.py
        run: python html_generate_expeditions.py
