name: Generate Expeditions Map

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache GPX folder
        uses: actions/cache@v4
        with:
          path: gpx
          key: gpx-cache-${{ hashFiles('**/*.py') }}
          restore-keys: |
            gpx-cache-

      - name: Run GeoJSON generator
        run: python geojson_generate_expeditions.py

      - name: Run HTML generator
        run: python html_generate_expeditions.py
